version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db

  webserver:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80" # access via http://localhost:8000
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: supplies_inventory
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  node:
    image: node:20
    container_name: laravel_node
    working_dir: /var/www/frontend
    volumes:
      - ./frontend:/var/www/frontend
    command: >
      sh -c "npm install && npm run dev"
    ports:
      - "5173:5173" # Vite default port for React

volumes:
  dbdata:
